use super::shell_escape_env;
use crate::{ActivePreset, ShellIntegrationStatus, PresetEnv};
use anyhow::{anyhow, Context, Result};
use std::{fs, path::PathBuf};

pub fn format_env(env: Vec<PresetEnv>) -> String {
    env.into_iter()
        .map(|item| format!("{}={}", item.env_name, shell_escape_env(&item.value)))
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn active_env_path() -> Result<PathBuf> {
    Ok(keydock_config_dir()?.join("active-env.sh"))
}

pub fn active_preset_path() -> Result<PathBuf> {
    Ok(keydock_config_dir()?.join("active-preset.json"))
}

pub fn current_active_preset() -> Result<Option<ActivePreset>> {
    let path = active_preset_path()?;
    if !path.exists() {
        return Ok(None);
    }
    let text = fs::read_to_string(path).context("read active preset state")?;
    serde_json::from_str(&text)
        .map(Some)
        .context("parse active preset state")
}

pub fn deactivate_active_preset() -> Result<()> {
    remove_if_exists(active_env_path()?)?;
    remove_if_exists(active_preset_path()?)?;
    Ok(())
}

pub fn shell_hook(shell: &str) -> Result<String> {
    match shell {
        "zsh" | "bash" => Ok(format!(
            r#"# KeyDock shell hook.
if [ -f "{active_env}" ]; then
  . "{active_env}"
fi"#,
            active_env = active_env_path()?.display()
        )),
        other => Err(anyhow!("unsupported shell: {other}")),
    }
}

pub fn install_shell_hook(shell: &str) -> Result<PathBuf> {
    let rc_path = shell_rc_path(shell)?;
    let begin = "# >>> keydock initialize >>>";
    let end = "# <<< keydock initialize <<<";
    // Write the direct source line so the hook works even when `keydock`
    // CLI is not on PATH.  The path is computed at install time from
    // the same config dir used by `write_active_env`.
    let snippet = format!("{begin}\n{}\n{end}\n", shell_hook(shell)?);
    let current = fs::read_to_string(&rc_path).unwrap_or_default();
    let without_old = remove_managed_block(&current, begin, end);
    let mut next = without_old.trim_end().to_string();
    if !next.is_empty() {
        next.push_str("\n\n");
    }
    next.push_str(&snippet);
    fs::write(&rc_path, next).with_context(|| format!("write {}", rc_path.display()))?;
    Ok(rc_path)
}

pub fn shell_integration_status(shell: &str) -> Result<ShellIntegrationStatus> {
    let rc_path = shell_rc_path(shell)?;
    let current = fs::read_to_string(&rc_path).unwrap_or_default();
    // Check for the managed block markers — this catches both old
    // (`eval "$(keydock hook zsh)"`) and new (direct source) formats.
    // The old format calls `keydock` at shell-start, which would hang
    // if the binary is missing or stuck.
    let installed = current.contains("# >>> keydock initialize >>>")
        && current.contains("# <<< keydock initialize <<<");
    Ok(ShellIntegrationStatus {
        shell: shell.to_string(),
        installed,
        rc_path: rc_path.display().to_string(),
    })
}

pub fn format_shell_exports(env: &[PresetEnv]) -> String {
    env.iter()
        .map(|item| format!("export {}={}", item.env_name, shell_escape_env(&item.value)))
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn keydock_config_dir() -> Result<PathBuf> {
    let dir = dirs::config_dir()
        .ok_or_else(|| anyhow!("cannot find platform config directory"))?
        .join("KeyDock");
    fs::create_dir_all(&dir).context("create KeyDock config directory")?;
    Ok(dir)
}

fn shell_rc_path(shell: &str) -> Result<PathBuf> {
    let home = dirs::home_dir().ok_or_else(|| anyhow!("cannot find home directory"))?;
    match shell {
        "zsh" => Ok(home.join(".zshrc")),
        "bash" => Ok(home.join(".bashrc")),
        other => Err(anyhow!("unsupported shell: {other}")),
    }
}

pub(crate) fn write_active_env(
    source_type: &str,
    id: &str,
    name: &str,
    env: &[PresetEnv],
) -> Result<()> {
    let active = ActivePreset {
        id: id.to_string(),
        name: name.to_string(),
        source_type: source_type.to_string(),
        env_count: env.len(),
        env_names: env.iter().map(|item| item.env_name.clone()).collect(),
    };
    let env_path = active_env_path()?;
    let preset_path = active_preset_path()?;
    let mut env_text = format!(
        "# Generated by KeyDock. This file contains plaintext secrets.\n# Active {source_type}: {name}\n"
    );
    env_text.push_str(&format_shell_exports(env));
    env_text.push('\n');
    fs::write(&env_path, env_text).with_context(|| format!("write {}", env_path.display()))?;
    fs::write(&preset_path, serde_json::to_string_pretty(&active)?)
        .with_context(|| format!("write {}", preset_path.display()))?;
    set_owner_read_write(&env_path)?;
    set_owner_read_write(&preset_path)?;
    Ok(())
}

fn remove_if_exists(path: PathBuf) -> Result<()> {
    match fs::remove_file(&path) {
        Ok(()) => Ok(()),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(err) => Err(err).with_context(|| format!("remove {}", path.display())),
    }
}

fn remove_managed_block(text: &str, begin: &str, end: &str) -> String {
    let Some(start) = text.find(begin) else {
        return text.to_string();
    };
    let Some(relative_end) = text[start..].find(end) else {
        return text.to_string();
    };
    let end_index = start + relative_end + end.len();
    let mut next = String::new();
    next.push_str(text[..start].trim_end());
    next.push('\n');
    next.push_str(text[end_index..].trim_start_matches(['\r', '\n']));
    next
}

#[cfg(unix)]
fn set_owner_read_write(path: &std::path::Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))
        .with_context(|| format!("chmod 600 {}", path.display()))
}

#[cfg(not(unix))]
fn set_owner_read_write(_path: &std::path::Path) -> Result<()> {
    Ok(())
}
